---
- name: 'Install gui packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - ubuntu-mate-desktop
    - mate-desktop-environment
    - mate-desktop-environment-extras
    - fonts-dejavu-core
    - fonts-dejavu-extra
    - i3
