---
- name: 'Install GUI environments'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - ubuntu-mate-desktop
    - compizconfig-settings-manager
    - mate-desktop-environment
    - mate-desktop-environment-extras
    - fonts-dejavu-core
    - fonts-dejavu-extra
    - i3

- name: 'Install tools and packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - chromium-browser
    - parcellite
    - gimp
    - redshift

- name: 'Purge GUI packages'
  apt: { name: "{{ item }}", state: absent }
  with_items:
    - tilda
    - thunderird
    - xul-ext-gdata-provider
    - xul-ext-lightning

- name: 'Update alternatives'
  alternatives:
    name: "{{ item[0] }}"
    link: "{{ item[1] }}"
    path: "{{ item[2] }}"
    priority: "{{ item[3] }}"
  with_nested: # STUPID Ansible defaults to flattening nested arrays if using with_items
    - - [ 'x-www-browser', '/usr/bin/x-www-browser', '/usr/bin/chromium-browser', '1000' ]
      - [ 'gnome-www-browser', '/usr/bin/gnome-www-browser', '/usr/bin/chromium-browser', '1000' ]

- name: 'Remove troublesome Python OpenSSL directory'
  file: { name: '/usr/lib/python2.7/dist-packages/OpenSSL/', state: absent }
