---
- name: 'Add apt keys by URL for GUI packages'
  apt_key: { url: "{{ item }}", state: present }
  loop:
    - 'https://dl.google.com/linux/linux_signing_key.pub'

- name: 'Add repos for latest GUI packages'
  apt_repository: { repo: "{{ item }}", mode: 644, state: present }
  loop: []
  # - 'deb xxxxxxx'

- name: 'Google Chrome insists on its apt sources.list file being EXACTLY like this'
  template:
    src: 'apt-google-chrome-list.j2'
    dest: '/etc/apt/sources.list.d/google-chrome.list'
    owner: root
    group: root
    mode: 0644

- name: 'Update apt cache (GUI packages)'
  apt: { update_cache: yes }
  changed_when: false

- name: 'Install GUI environments and packages'
  apt:
    name:
      - ubuntu-mate-desktop
      - compizconfig-settings-manager
      - mate-desktop-environment
      - mate-desktop-environment-extras
      - libmetacity1
      - metacity-common
      - fonts-dejavu-core
      - fonts-dejavu-extra
      - xserver-xorg-input-synaptics
      # - shutter # TODO
    state: latest

- name: 'Install tools and packages'
  apt:
    name:
      - parcellite
      - xdotool
      - gimp
      - redshift
      - google-chrome-stable
    state: latest

- name: 'Purge GUI packages'
  apt: { name: "{{ packages_to_block }}", state: absent }

- name: 'Update alternatives'
  alternatives:
    name: "{{ item[0] }}"
    link: "{{ item[1] }}"
    path: "{{ item[2] }}"
    priority: "{{ item[3] }}"
  loop:
    - [ 'x-www-browser', '/usr/bin/x-www-browser', '/usr/bin/google-chrome', '1001' ]
    - [ 'gnome-www-browser', '/usr/bin/gnome-www-browser', '/usr/bin/google-chrome', '1001' ]
