---
- hosts: all
  become: true
  roles:
    - role: main-user
      vars:
        name: "{{ main_user_name }}"
        uid: "{{ main_user_uid }}"
        gid: "{{ main_user_gid }}"
        homedir: "{{ main_user_homedir }}"
        comment: "{{ main_user_comment }}"
      tags: main-user
    - { role: base-packages, tags: base-packages }
    - { role: common-packages, tags: common-packages }
    - { role: go, tags: go }
    - { role: rbenv, vars: {user_name: "{{ main_user_name }}", homedir: "{{ main_user_homedir }}"}, tags: rbenv }
    - { role: pyenv, vars: {user_name: "{{ main_user_name }}", homedir: "{{ main_user_homedir }}"}, tags: pyenv }
    - { role: docker, tags: docker }
    - { role: phantomjs, tags: phantomjs }
    - { role: scripts }
    - { role: system, tags: system }

- hosts: gui
  become: true
  roles:
  - { role: gui, tags: gui }

- hosts: all
  become: true
  tasks:
    - name: 'Remove unused packages'
      apt: { autoremove: yes }
