---
- hosts: localhost
  become: true
  roles:
    - { role: first-steps }
    - { role: main-user, name: ayqazi, uid: 1000, gid: 1000, homedir: /home/ayqazi }
    - { role: base-packages }
    - { role: common-packages }
    - { role: scripts }
    - { role: gui }
