---
- name: "Create wsl.env file for main user"
  template:
    src: "wsl.sh.j2"
    dest: "{{ main_user_homedir }}/.bashrc.d/wsl.sh"
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"
    mode: 0644

- name: "Install /etc/wsl.conf"
  template:
    src: "wsl.conf.j2"
    dest: "/etc/wsl.conf"
    owner: root
    group: root
    mode: 0644
