---
- name: 'Add partner repo'
  apt_repository:
    repo: "deb http://archive.canonical.com/ubuntu {{ ubuntu_distribution }} partner"
    mode: 0644
    state: present

- name: 'Upgrade all packages'
  apt: { update_cache: yes, upgrade: dist }

- name: 'Install useful common packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - debconf-utils         # Diagnostics via debconf-get-selections
    - dstat                 # Get pretty system statistics like disk space, CPU usage, etc.
    - python-pycurl         # Needed by Ansible for URL fetching

- name: 'Install common development packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
