---
- name: "Add Docker repo key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    state: present

# TODO Move distro name in repo back to '{{ ubuntu_distribution }}' once they support it
- name: "Add Docker repo"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present

- name: "Stop Docker in case it is running"
  service: { name: docker, state: stopped }
  ignore_errors: true

- name: "Delete PID file in case it does not automatically go away"
  file: { name: "/var/run/docker-ssd.pid", state: absent }

- name: "Update apt and install Docker tools"
  apt:
    name: "docker-ce"
    state: present
    force: yes
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: "Add main user to Docker group"
  user:
    name: "{{ main_user_name }}"
    groups: "docker"
    append: true
