---
- name: 'Install sudoers file'
  template:
    src: 'sudoers.j2'
    dest: '/etc/sudoers'
    owner: root
    group: root
    mode: 0440
    validate: '/usr/sbin/visudo -csf %s'
  tags: sudoers

- name: 'Bump inotify limit (applied on reboot)'
  copy:
    content: "fs.inotify.max_user_watches = {{ system_inotify_max_user_watches }}\n"
    dest: '/etc/sysctl.d/60-fs-inotify-max-user-watches.conf'
    owner: root
    group: root
    mode: 0644

- name: 'Fix netplan if it is grabbing our WiFi'
  template:
    src: 'netplan-netcfg.yaml'
    dest: '/etc/netplan/01-netcfg.yaml'
    owner: root
    group: root
    mode: 644
  notify:
    - netplan-generate
    - netplan-apply
    - reboot-warning
