---
- name: 'Add repos for latest development packages'
  apt_repository: { repo: "{{ item }}", mode: 644, state: present }
  with_items:
    - ppa:webupd8team/java
    - ppa:git-core/ppa

- name: 'Accept licenses'
  debconf:
    name: '*'
    question: "{{ item }}"
    value: true
    vtype: select
  with_items:
    - shared/accepted-oracle-license-v1-1
    - msttcorefonts/accepted-mscorefonts-eula

- name: 'Install commonly used requirements for building other packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - build-essential
    - bison
    - pkg-config

- name: 'Install commonly used development libraries'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - openjdk-8-jdk
    - libyaml-dev
    - sqlite3
    - libgdbm-dev
    - libncurses5-dev
    - libffi-dev
    - libmath-round-perl # needed by ayqpw

- name: 'Install commonly used packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - schedtool
    - pbzip2
    - pv
    - dstat
    - nethogs
    - jq
    - netcat-traditional
    - openssh-client
    - openssh-server
    - openssh-blacklist-extra

- name: 'Install tools used for development'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - git
    - emacs24
    - emacs24-el
    - emacs-goodies-el
