---
- name: 'Add apt keys by URL for common packages'
  apt_key: { url: "{{ item }}", state: present }
  with_items:
    - 'https://swupdate.openvpn.net/repos/repo-public.gpg'
    - "{{ apt_keys }}"

- name: 'Add repos for latest common packages'
  apt_repository: { repo: "{{ item }}", mode: 644, state: present }
  with_items:
    - ppa:webupd8team/java
    - ppa:git-core/ppa
    - "deb http://build.openvpn.net/debian/openvpn/stable {{ ubuntu_distribution }} main"
    - "{{ apt_repositories }}"

- name: 'Accept licenses'
  debconf:
    name: '*'
    question: "{{ item }}"
    value: true
    vtype: select
  with_items:
    - shared/accepted-oracle-license-v1-1
    - msttcorefonts/accepted-mscorefonts-eula

- name: 'Update apt cache'
  apt: { update_cache: yes }

- name: 'Install commonly used requirements for building other packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - build-essential
    - bison
    - pkg-config

- name: 'Install commonly used dev libraries, dev tools, and packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - openjdk-8-jdk
    - libyaml-dev
    - sqlite3
    - libsqlite3-dev
    - libgdbm-dev
    - libncurses5-dev
    - libmath-round-perl # needed by ayqpw
    - libbz2-dev
    - libpq-dev

    - schedtool
    - pbzip2
    - pv
    - dstat
    - nethogs
    - jq
    - netcat-traditional
    - openssh-client
    - openssh-server
    - openssh-blacklist-extra
    - bash-completion
    - python-wheel
    - python3
    - python3-venv
    - python3-pip
    - curl
    - linux-tools-generic
    - linux-cloud-tools-generic
    - parallel
    - whois
    - clamav
    - openvpn

    - git
    - git-crypt
    - emacs24
    - emacs24-el
    - emacs-goodies-el
    - postgresql-client-9.5
    - postgresql-9.5

    - "{{ apt_packages }}"

- name: 'Install debs not in repos'
  apt: { deb: "{{ item }}" }
  with_items: "{{ debs }}"
  tags: debs

- name: 'Install some pip packages for Python 2'
  pip: { name: "{{ item }}", state: present }
  with_items:
    - pyOpenSSL
    - wheel

- name: 'Install some pip packages for Python 3'
  pip: { name: "{{ item }}", state: present, executable: /usr/bin/pip3 }
  with_items:
    - pyOpenSSL
    - wheel
