---
- name: 'Add apt keys by URL for common packages'
  apt_key: { url: "{{ item }}", state: present }
  loop: "{{ apt_keys | dictsort | map('last') | list }}"

- name: 'Add repos for latest common packages'
  apt_repository: { repo: "{{ item }}", mode: 644, state: present }
  loop: "{{ apt_repositories | dictsort | map('last') | list }}"

- name: 'Accept licenses'
  debconf:
    name: '*'
    question: "{{ item }}"
    value: 'true'
    vtype: select
  loop: "{{ apt_licenses | dictsort | map('last') | list }}"

- name: 'Update apt cache'
  apt: { update_cache: yes }

- name: 'Install commonly used requirements for building other packages'
  apt: { name: "{{ item }}", state: latest }
  loop:
    - build-essential
    - bison
    - pkg-config

- name: 'Install commonly used dev libraries, dev tools, and packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - libyaml-dev
    - sqlite3
    - libsqlite3-dev
    - libgdbm-dev
    - libncurses-dev
    - libmath-round-perl # needed by ayqpw
    - libbz2-dev
    - libpq-dev

    - gpg
    - gnupg

    - schedtool
    - zip
    - unzip
    - pbzip2
    - pv
    - dstat
    - nethogs
    - jq
    - netcat-traditional
    - openssh-client
    - openssh-server
    - bash-completion
    - python3
    - python3-venv
    - python3-pip
    - curl
    - linux-tools-generic
    - linux-cloud-tools-generic
    - parallel
    - whois
    - clamav
    - openvpn
    - socat

    - "{{ emacs_package_name }}"
    - emacs-el
    - emacs-goodies-el

- name: 'Install packages'
  apt: { name: "{{ apt_packages | dictsort | map('last') | list }}", state: latest }
  tags: packages

- name: 'Install debs not in repos'
  apt: { deb: "{{ item }}" }
  loop: "{{ debs }}"
  tags: debs

- name: 'Install some pip packages for Python 3'
  pip: { name: "{{ item }}", state: present, executable: /usr/bin/pip3 }
  loop:
    - pyOpenSSL
    - wheel
