---
- name: "Download phantomjs archive"
  unarchive:
    src: "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-{{ phantomjs_version }}-linux-x86_64.tar.bz2"
    remote_src: true
    dest: "/var/tmp"
    owner: root
    group: root
    mode: 0644

- name: "Install phantomjs binary"
  copy:
    src: "/var/tmp/phantomjs-{{ phantomjs_version }}-linux-x86_64/bin/phantomjs"
    remote_src: true
    dest: "/usr/local/bin/phantomjs"
    owner: root
    group: root
    mode: 0755
