---
- name: 'Check if desired version of Go is already installed'
  command: 'fgrep -q go{{ go_version }} /usr/local/go/VERSION'
  register: checkversion
  ignore_errors: true
  changed_when: false

- name: 'Download Go binary'
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    owner: root
    group: root
    mode: 0644
  when: checkversion.rc != 0

- name: 'Delete existing directory'
  file: { name: '/usr/local/go', state: absent }
  when: checkversion.rc != 0

- name: 'Extract Go archive'
  unarchive:
    src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    remote_src: yes
    dest: '/usr/local'
    extra_opts: ['go'] # Just extract the go directory - just in case there is something else in there
    creates: '/usr/local/go'
  when: checkversion.rc != 0

- name: 'Symlink executables into /usr/local/bin'
  file:
    src: "/usr/local/go/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    owner: root
    group: root
    mode: 0755
  with_items:
    - go
    - gofmt
