
- name: 'Install essential packages'
  apt: { name: "{{ item }}", state: latest }
  with_items:
    - debconf-utils         # Diagnostics via debconf-get-selections
    - python-pycurl         # Needed by Ansible for URL fetching
