---
- name: 'Create user dir'
  file: { name: "{{ homedir }}", state: directory, owner: "{{ uid }}", group: "{{ gid }}", mode: 0770 }

- name: 'Customize the user further'
  user:
    name: "{{ name }}"
    groups: "{{ main_user_default_groups + main_user_extra_groups }}"
    append: true
    comment: "{{ comment }}"
