---
- name: 'Checkout/update rbenv'
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: "{{ homedir }}/.rbenv"
    update: yes
    version: master
  become: yes
  become_user: "{{ user_name }}"

- name: 'Checkout/update ruby-build as rbenv plugin'
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: "{{ homedir }}/.rbenv/plugins/ruby-build"
    update: yes
    version: master
  become: yes
  become_user: "{{ user_name }}"
